source 'https://rubygems.org'

gem 'cli-kit', '~> 3.1.0'
gem 'cli-ui', '~> 1.1.4'

group :test do
  gem 'mocha', '~> 1.5.0', require: false
  gem 'minitest', '>= 5.0.0', require: false
  gem 'minitest-reporters', require: false
end
